[package]
name = "Jailer"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "0.12.12", features = ["json"]}
serde = {version = "1.0.217", features = ["derive"]}
structopt = "0.3.26"
tokio = {version = "1.43.0", features = ["full"]}
Justice = { path = "../Justice" }
